### ISSUE TITLE
Pressure plates and permissions

### ISSUE THREAD

**Issue by SnowBlitzz** [MinecraftPortCentral/GriefPrevention#14] opened 2016-04-05 15:25 UTC
Aside from what's already reported, I've found out that pressure plates inside a person's claim can be triggered by a non-owner or non-trusted player by throwing an item on it. 

Also I would like to request short descriptions to be placed above a permission node here https://github.com/MinecraftPortCentral/GriefPrevention/blob/master/src/me/ryanhamshire/griefprevention/GPPermissions.java so it is more understandable.

**Comment by bloodmc** [comment] 2016-04-07 23:31
@SnowBlitzz I'll fix the pressure plate bug soon. I'll update the descriptions soon as well =). Keep the tickets coming so GriefPrevention can get a stable release.

Thanks!

**Comment by bloodmc** [comment] 2016-04-08 02:31
@SnowBlitzz I cannot reproduce this issue. Are you sure the player doesn't have permissions? Please test with a new player that has bare minimal perms. Also to make sure you are using latest build, please grab this

https://www.dropbox.com/s/e6mprcvnxhstc6g/griefprevention-12.7.1-SpongeTest-B2.jar?dl=0

**Comment by SnowBlitzz** [comment] 2016-04-13 08:01
To reproduce the issue, let's say there are 2 players. Player A and Player B
Player A claim an area, places a door and a pressure plate inside his claim
Player B steps on pressure plate, nothing happens - Working good
Player B throws an item on the pressure plate, door opens - Shouldn't happen (?)

**Comment by bloodmc** [comment] 2016-04-13 20:31
I just retested this and it seems to be fixed with my latest fixes.

https://www.dropbox.com/s/vp31g9cwiumj2dz/griefprevention-12.7.1-SpongeTest-B4.jar?dl=0

**Closed by bloodmc** 2016-04-13 20:31 UTC
