### ISSUE TITLE
Compatibility issue - RFTools elevator - Server timeout/freeze

### ISSUE THREAD

**Issue by rob5251** [MinecraftPortCentral/GriefPrevention#587] opened 2018-01-31 01:39 UTC
Mod Versions
GP: 4.3.0.529
LP:  4.0.121
SpongeForge: 1.12.2-2586-7.1.0-BETA-2862
RFTools: 1.12.2-7.27
(Works as intended in RFTools build 7.26)

GP and RFTools elevators are no longer getting along
Since I updated to the latest version of RFTools the elevator no longer works, the platform will go to move then the server gets hung up and times out everyone on the server. After this occurs the server needs to be reset before anyone can join again. The last thing to be spit out in the console when this occurs is the following:

[22:31:49] [Server thread/WARN] [Sponge]: No entity type is registered for class net.minecraftforge.common.util.FakePlayer

At first I thought it was an issue with RFTools itself, but after removing mods and screwing around I narrowed it down to the issue only occurring when GP was on the server.

Here is a run of gpdebug with lpverbose on (This is right after the elevator button is hit and the platform is set in motion):
https://gist.githubusercontent.com/anonymous/b66af75a12182cd65df0b2209d1cd323/raw/c39f7334c9d3de81e36a449e5aff9842e6f30ee5/gpdebug.txt

**Comment by Eufranio** [comment] 2018-01-31 01:41
Can you take a timings/warmroast report?

**Comment by rob5251** [comment] 2018-01-31 01:42
Sure, just let me know how.

**Comment by Eufranio** [comment] 2018-01-31 01:45
Timings: https://docs.spongepowered.org/stable/en/server/spongineer/commands.html#timings
WarmRoast: https://github.com/sameer/WarmRoastSetup
Preferably WarmRoast.

**Comment by rob5251** [comment] 2018-01-31 02:07
WarmRoast seems a bit too advanced for my dumb ass; unfortunately.
However here is the timings report:
https://timings.aikar.co/?id=8d11873f9e8849d0a6d759c72bc0ddd4#timings

**Comment by rob5251** [comment] 2018-01-31 02:10
Oh I was actually able to get a crash report for once:
https://gist.github.com/rob5251/4aefa01ab70c2602cdc6871680852a75

**Comment by bloodmc** [comment] 2018-01-31 14:56
@rob5251 Odd GP isn't in that trace but we can do some testing. Try disabling protection modules 1 by 1 until the issue resolves itself. You can find the protection modules in GP's global config. Let me know which module is causing the issue.

**Comment by rob5251** [comment] 2018-01-31 23:13
Just finished testing it. I went through each module, tried a few combinations, and turned all off. The problem persist no matter what.

Removing the GriefPrevention plugin is the only way it will work right now.


I think the issue is stemming from their recent changes to the elevator/builder entity, not sure if you can notice anything in their code that might lead to a solution.
https://github.com/McJty/RFTools/blob/19f938d39f9b1e5abf3200f47e7961f63d112092/src/main/java/mcjty/rftools/blocks/builder/BuilderTileEntity.java

**Comment by rob5251** [comment] 2018-02-03 01:41
I did a bit of extra testing and found that if the elevator block is activated with a redstone signal then things work properly. However if the elevator is activated via an "elevator button module" in a "screen" the issue occurs.

When the elevator block is activated via a redstone signal gp is detecting it as a player action, however when the "elevator button module" is used it acts as a fake player "rftools_builder".

_gpdebug when using redstone signal:_
https://gist.github.com/rob5251/d630e7765c5a081e077d25e880ac8372

**Comment by bloodmc** [comment] 2018-02-03 18:17
Your crash report shows the watchdog killing server. Try testing with 'max-tick-time' set to -1. I wasn't able to reproduce this issue using latest RFTools and a simple elevator setup within a claim.

**Comment by rob5251** [comment] 2018-02-03 19:54
Here you go:
[World.zip](https://drive.google.com/file/d/16lKDel4JEM2Y4KoDu85-hhdmSA5ynZnx/view?usp=sharing)

**Comment by bloodmc** [comment] 2018-02-03 20:43
This issue is caused by RFTools when Forge's 'BlockEvent.BreakEvent' is cancelled. GP cancels the event during this call https://github.com/McJty/RFTools/blob/1.12/src/main/java/mcjty/rftools/blocks/builder/BuilderTileEntity.java#L1103

Once cancelled, RFTools gets stuck in a loop which needs to be fixed on their end.

**Comment by rob5251** [comment] 2018-02-03 20:58
Thanks for taking the time to work on this issue; I'll see if they can get a fix worked out on their end now.
👍

**Comment by josephcsible** [comment] 2018-02-04 01:01
@bloodmc Thanks for the detailed diagnosis. With it, I was able to reproduce the issue with RFTools' own block protection that cancels that event, without having Sponge installed at all. This issue can be closed.

**Closed** 2018-02-04 01:08 UTC
