### ISSUE TITLE
Sometimes the owner is shown a message that he can not use the item

### ISSUE THREAD

**Issue by ziceptor** [MinecraftPortCentral/GriefPrevention#644] opened 2018-04-26 02:41 UTC
Reproduce. Put an egg in inventory and quickly click the right-wing or leftist button of a mouse on him several times. 

![](https://i.imgur.com/cVoN2nl.png) 

![](https://i.imgur.com/keXMGxo.png)

![](https://i.imgur.com/Xbe9Y6t.png)

![](https://i.imgur.com/R5LGc7e.png)

forge-1.12.2-14.23.2.2611-universal.jar
spongeforge-1.12.2-2611-7.1.0-BETA-3008.jar
LuckPerms-Sponge-4.1.80.jar
griefprevention-1.12.2-4.3.0.574.jar

**Comment by bloodmc** [comment] 2018-04-28 04:11
Unable to reproduce. Test on a clean server with ONLY GP/LP/SF and provide steps.

**Comment by ziceptor** [comment] 2018-05-22 09:53
I can't understand the relationship.

` with ONLY GP/LP/SF`

no problem

I found a plugin where the problem often occurs. @SimonFlash

forge-1.12.2-14.23.3.2655-universal.jar
spongeforge-1.12.2-2655-7.1.0-BETA-3082.jar
LuckPerms-Sponge-4.2.12.jar
griefprevention-1.12.2-4.3.0.579.jar
+
ActiveTime-s7.1-v1.4.2.jar

**Comment by SimonFlash** [comment] 2018-05-22 19:37
I can't imagine a single reason why ActiveTime could be directly related to this - I have no listeners in any of these areas and don't perform any actions related to inventories or items. There has not been evidence provided to show proof of ActiveTime's involvement, so I will be closing the issue there until there is a justifiable reason to believe that ActiveTime is related to this issue.

**Comment by ziceptor** [comment] 2018-05-23 01:41
@SimonFlash thanks for the comment. I'm surprised too But this happens with your plugin. Waiting for a response from @bloodmc

**Comment by ziceptor** [comment] 2018-05-23 07:03
@SimonFlash You asked for proof. Only video (subtitles): https://youtu.be/dpscQBwfWmA

ps Error loading server of a different kind. https://github.com/SpongePowered/SpongeCommon/issues/1906

Sorry for bad English

**Comment by ziceptor** [comment] 2018-05-25 15:31
Can anyone debug this in the IDE?

**Comment by bloodmc** [comment] 2018-06-11 17:09
@ziceptor Does this still occur in latest GP/SF? I am unable to reproduce the issue on my end with only SF/GP/LP.

**Comment by ziceptor** [comment] 2018-06-15 16:30
ok

**Closed** 2018-07-06 06:02 UTC
