### ISSUE TITLE
Claims disappearing 

### ISSUE THREAD

**Issue by NoCross1** [MinecraftPortCentral/GriefPrevention#124] opened 2016-08-05 17:25 UTC
Hey, I believe I found out what makes the claims disappear. I posted on the sponge forums thread but I was told to post here, so basically a player reported this to me on our forum "*MAJOR UPDATE*
i discover the claims become unclaimed when the owner of the claim goes offline
not 100% sure but i went throu vanellope_glitch town and Reconkevin house which both are claimed but magicly not claimed
Update*
The house become claimed again when they get back"

Spongeforge: 1.8.9 1653
GriefPrevention 1.8.9 1.0.0.56

**Comment by bloodmc** [comment] 2016-08-05 19:08
@NoCross1 I just tested this and I cannot reproduce it. Post your permissions.json file

**Comment by NoCross1** [comment] 2016-08-05 19:14
Alright, my permissions file is super messy. https://www.dropbox.com/s/egnfv75yphc3i49/permissions.json?dl=0

**Comment by NoCross1** [comment] 2016-08-05 19:29
Okay so another thing is that a player has said "It was fine until I started doing subdivisions in other claims" when his claim was corrupt where players can't claim over that claim but can break blocks etc.

**Comment by bloodmc** [comment] 2016-08-05 19:34
@NoCross1 There are a bunch of issues with this...

1. Turn on alphabetize in the pex config so all your perms get sorted.
2. Remove "griefprevention.admin.claim.wilderness" from the default user as this is an ADMIN only function and should never be given to all players.
3. Helper has the godmode permission "griefprevention.admin.command.ignore-claim" which should only be given to the highest admins on server. This command lets you bypass all protection in GP.
4. I see the perm "griefprevention.claims.flag" which should NEVER be assigned to anyone. This essentially is granting all flags. GP assigns this via the flag commands using contexts, never assign them yourself.
5. "permissions-default": -1 , as I stated in the changelog, you should never have any group/user with a default of -1, use 0 instead.

**Comment by NoCross1** [comment] 2016-08-05 19:37
Alright, so the claims getting corrupt is being caused by the permissions file?

**Comment by NoCross1** [comment] 2016-08-05 21:32
Hey, after doing what you said this problem is still occurring. Any ideas?

**Comment by bloodmc** [comment] 2016-08-05 22:30
@NoCross1 Zip your GriefPreventionData folder in world folder. Provide a link here and tell me the location of the claim.

**Comment by NoCross1** [comment] 2016-08-06 01:35
Hey, it hasn't been updated since 7/28 is this because I use mysql? https://www.dropbox.com/s/aazu4tqgxui5znf/GriefPreventionData.zip?dl=0

**Comment by NoCross1** [comment] 2016-08-07 01:22
Any idea on this problem? Claims keep disappearing and it's just making me lose my most loyal players.

**Comment by bloodmc** [comment] 2016-08-07 04:14
@NoCross1 mysql is not functional with GP. You need to use file mode.

**Comment by NoCross1** [comment] 2016-08-07 06:28
Is there a command to migrate the files if it was working or can I just remove mysql and not worry about data?

**Closed** 2016-08-08 05:23 UTC
