### ISSUE TITLE
[1.10.2] Players able to access OpenComputer's computers

### ISSUE THREAD

**Issue by Eufranio** [MinecraftPortCentral/GriefPrevention#187] opened 2016-10-21 22:02 UTC
Players are able to open and interact with computers inside a protected claim.

**Comment by inklit** [comment] 2016-10-21 23:28
This is also a problem on 1.8.9.

**Comment by bloodmc** [comment] 2016-10-25 01:17
@Eufranio This works fine for me, did you give players /containertrust or /accesstrust ? because this overrides the flags.

**Comment by Eufranio** [comment] 2016-10-25 01:20
Nope. I tested going to a player base (where I don't have permissions, and being in the members rank). I wasn't able to open chests/use items/containers and stuff, but I was able to open the computer. The message shows up, but the GUI still opening. I'm using LuckPerms in MySQL mode, and the permissions are working.
A point, the GUI of the screen opens very fast, the opening doesn't seem to wait the server check (if the player is able to open), that's why I suggest sending a packet to close the GUI...

**Comment by Eufranio** [comment] 2016-10-25 01:23
Also, I'm using GriefPrevention 2.1.0.83, Minecraft 1.10.1, and SpongeForge 5.1.0-BETA-1814

**Comment by bloodmc** [comment] 2016-10-25 01:32
Give me the exact block id that you are testing with. Also, you need to update to latest SF build and retest.

**Comment by bloodmc** [comment] 2016-10-25 01:34
Also make sure you are using a recent version of LuckPerms as older ones had some bugs.

https://ci.lucko.me/job/LuckPerms/

I only tested with PEX where everything worked as expected.

**Comment by Eufranio** [comment] 2016-10-25 01:47
I am using latest LuckPerms, tomorrow I give you the ID and update SpongeForge, too late atm xD

**Comment by inklit** [comment] 2016-10-25 02:16
@bloodmc Please test with a computer monitor with a keyboard attached. I believe that is what he is referring to, not computer cases.

I tested this on 1.8.9 with PermissionsEx and it's an issue there too.

**Comment by bloodmc** [comment] 2016-10-27 05:46
@Eufranio @inklit This was caused by OpenComputers only opening the GUI on client-side and never telling the server about it as seen here

https://github.com/MightyPirates/OpenComputers/blob/master-MC1.10/src/main/scala/li/cil/oc/common/block/Screen.scala#L86

I pushed a fix for this in SpongeForge. Update to 1845+

**Closed by bloodmc** 2016-10-27 05:46 UTC
