### ISSUE TITLE
OpenBlocks Gravestones Can't Spawn in Protection

### ISSUE THREAD

**Issue by Sir-Will** [MinecraftPortCentral/GriefPrevention#664] opened 2018-05-27 15:19 UTC
hey,
the OpenBlocks gravestones don't spawn in protected claims as the mod checks if it can modify the block: https://github.com/OpenMods/OpenBlocks/blob/83d6f513609bdf9ec131325f67ce468d6554fa34/src/main/java/openblocks/common/PlayerDeathHandler.java#L112 and if it can't it drops the items instead of creating a gravestone.

Is there any way to change that? I already have `openblocks:grave` in the `global-target` blacklist.

**Comment by bloodmc** [comment] 2018-05-27 15:58
Not something I would want to deal with. It makes more sense to simply ask the mod dev to provide a config to disable the check.

**Comment by Sir-Will** [comment] 2018-05-28 03:55
Alright. Would there be any reason to keep item-spawn protection enabled? As this causes issues with graves not dropping items.

**Comment by bloodmc** [comment] 2018-05-28 06:26
item-spawn was added to prevent dupes which are mostly fixed in Sponge now. If you have no need for it then disable the module.

**Comment by Sir-Will** [comment] 2018-05-28 18:05
> item-spawn was also added to prevent dupes which are mostly fixed in Sponge now. If you have no need for it then disable the module.

That was the answer I was looking for, thanks.

**Comment by Sir-Will** [comment] 2018-06-30 01:20
So I had to reenable item-spawn as it allowed duping of machines with wrenches but now it doesn't spawn graves again because of this. I already have `openblocks:grave` in the blacklist (`global-source` and `global-target`).

**Comment by bloodmc** [comment] 2018-07-01 22:02
`item-spawn` should have no effect on spawning graves as the check happens before `item-spawn` is even checked

https://github.com/MinecraftPortCentral/GriefPrevention/blob/master/src/main/java/me/ryanhamshire/griefprevention/listener/EntityEventHandler.java#L224

**Comment by bloodmc** [comment] 2018-07-01 22:05
Oh yes I remember now, the issue is with the mod's check. You need to report to the OpenGraves dev to add config to disable his check to support protection mods/plugins.

**Closed by bloodmc** 2018-07-01 22:05 UTC

**Comment by Sir-Will** [comment] 2018-07-01 23:45
Which check do you mean? The "GraveStone Mod" does have the same issue btw, just spawns an empty grave because of the item-spawn.
