### ISSUE TITLE
Heavy lag caused by minecraft:powered_repeater

### ISSUE THREAD

**Issue by PolyacovYury** [MinecraftPortCentral/GriefPrevention#764] opened 2018-08-28 20:02 UTC
Timing report:
```
Minecraft::minecraft:powered_repeater | count(9177)  total(8.76% 85.551s, 17.51% of tick) | avg(9.32ms per - 8.75ms/0.94 per tick)
griefprevention::onBlockNotify | count(1901514)  total(0.18% 1.791s, 0.37% of tick) | avg(0.00ms per - 0.18ms/194.59 per tick)
```
This seemed to appear on recent update from build 579 to build 646.

**Comment by PolyacovYury** [comment] 2018-08-28 20:35
Answering some questions asked there - all of the behaviours I showed are not directonal and are completely intentional vanilla mechanics. And I didn't quite understand on why did I need to provide a world save for 2 contraptions, 1 of which is 1-wide and one can be googled up by "2x2 flush piston door".

**Comment by bloodmc** [comment] 2018-08-30 21:50
`griefprevention::onBlockNotify | count(1901514)  total(0.18% 1.791s, 0.37% of tick) | avg(0.00ms per - 0.18ms/194.59 per tick)`

This shows GP onBlockNotify is only using avg 0-0.18ms so GP is not responsible according to the timing you posted.

**Comment by bloodmc** [comment] 2018-09-01 00:40
This wasn't the case in older sponge builds as there was a special case for it to fire as `ChangeBlockEvent.Modify`. So its a regression bug in Sponge that will need to be fixed. Has nothing to do with GP.

**Comment by bloodmc** [comment] 2018-09-01 21:26
Please create a SpongeCommon ticket with a test world that can reproduce the redstone lag. I'll close this ticket since it isn't an issue in GP.

**Closed by bloodmc** 2018-09-01 21:26 UTC
