### ISSUE TITLE
Players can void liquids from ExUtils2 drums

### ISSUE THREAD

**Issue by Eufranio** [MinecraftPortCentral/GriefPrevention#263] opened 2016-12-30 23:16 UTC
Not sure if it's a issue with GriefPrevention or ExtraUtils2 itself, but whenever a player tries to break a drum with liquids inside and doesn't have permission for, the liquids are voided.

**Comment by bloodmc** [comment] 2016-12-31 07:51
Cannot reproduce with my current SF and GP build so probably fixed once i release it.

**Comment by bloodmc** [comment] 2018-01-24 02:51
This should no longer be an issue in latest builds.

**Closed by bloodmc** 2018-01-24 02:51 UTC
