### ISSUE TITLE
Gravel in debug

### ISSUE THREAD

**Issue by SnowBlitzz** [MinecraftPortCentral/GriefPrevention#584] opened 2018-01-28 08:45 UTC
https://gist.github.com/anonymous/f38bcd52248d29a34e4e0abb2620e527
4 seconds, tons of gravel lines. Nobody is actually touching any gravel.

Did a debug earlier with just one person. He was testing throwing poke balls in the ground so obviously no gravel interaction either, but the debug is spammed by gravel https://gist.github.com/anonymous/6fc928c55e0502645cea571efe6b609a

**Comment by bloodmc** [comment] 2018-01-28 15:38
Reproduce on a clean server. It looks like a tracking bug in Sponge.

**Comment by bloodmc** [comment] 2018-02-13 04:37
Closing as i'm unable to reproduce this with a clean server. If it does happen, it's probably a tracking bug in Sponge.

**Closed by bloodmc** 2018-02-13 04:37 UTC
