### ISSUE TITLE
Regular claims within an admin claim (not subdivison)

### ISSUE THREAD

**Issue by KhaozFrost** [MinecraftPortCentral/GriefPrevention#564] opened 2018-01-13 00:51 UTC
[gp.zip](https://github.com/MinecraftPortCentral/GriefPrevention/files/1627916/gp.zip)
I'm able to create claims within each other (non- subdivisions)

spongeforge-1.12.2-2555-7.0.0-BETA-2800.jar
Pixelmon Reforged
griefprevention-1.12.2-4.3.0.511.jar

Reproduce:
- clean instance
-created admin claim
-created player claim inside it
-created player claim inside the player claim

**Comment by bloodmc** [comment] 2018-01-15 18:03
@KhaozFrost Unable to reproduce this using latest LP/SF/GP.

Created admin claim
Created basic claim within admin claim
Could not create a basic claim within the basic claim.
GP sends overlap message to player.

**Comment by bloodmc** [comment] 2018-01-24 20:43
Rasgnarok tested and couldn't reproduce as well. Closing until you can provide steps that can be reproduced with latest builds.

**Closed by bloodmc** 2018-01-24 20:43 UTC
